const CONFIG = {
    WALLET_COUNT: 5,
    TXFEE: 0.02,
    BNB_MIN_AMOUNT: 0.3,
    BNB_MAX_AMOUNT: 0.5,
    TOKEN_MIN_AMOUNT: 5000,
    TOKEN_MAX_AMOUNT: 10000,
    TRADE_INTERVAL_IN_MINUTE: 2,
}

export default CONFIG;